language: node_js
node_js:
  - "6"
  - "7"
script: 
  - npm install
  - npm run typecheck

deploy:
  provider: npm
  email: huttarichard@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
